environment:
  PYTHON: "C:\\Python37"
  REPOSITORY_KEY:
    secure: 3jorWUxqWjnR0X8Ye5NsAurPzickp84H2a+/ILwlRA3EQXzv+jo+kv9tvI1YKyTE
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
      CONAN_VISUAL_VERSIONS: 16

cache:
  - '%LOCALAPPDATA%\pip\Cache'

platform: x64

install:
  - git submodule update --init --recursive
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  # Conan
  - cmd: pip.exe install conan --quiet --upgrade --upgrade-strategy only-if-needed
  - cmd: pip.exe install conan_package_tools --quiet --upgrade --upgrade-strategy only-if-needed
  - cmd: refreshenv
  # Workaround - force update cmake and visual for 2019 support
  - cmd: choco upgrade cmake
  - ps: if ($env:CONAN_VISUAL_VERSIONS -eq 16)
        {
          choco install visualstudio2019buildtools visualstudio2019-workload-vctools
        }
  - cmd: conan user # It creates the conan data directory
  # Workaround - copy fallback settings with Visual Studio 2019 enabled
  - cmd: move conan-fallback-settings.yml %USERPROFILE%/.conan/settings.yml

build_script:
  - cmd: conan --version
  - cmd: python build.py %REPOSITORY_KEY%